cyoa-step1: cyoa-step1.cpp page.hpp
	g++ -o cyoa-step1 -ggdb3 -std=gnu++98 -Wall -Werror -pedantic cyoa-step1.cpp
cyoa-step2: cyoa-step2.cpp page.hpp story.hpp
	g++ -o cyoa-step2 -ggdb3 -std=gnu++98 -Wall -Werror -pedantic cyoa-step2.cpp
cyoa-step3: cyoa-step3.cpp page.hpp story.hpp
	g++ -o cyoa-step3 -ggdb3 -std=gnu++98 -Wall -Werror -pedantic cyoa-step3.cpp
cyoa-step4: cyoa-step4.cpp page.hpp story.hpp
	g++ -o cyoa-step4 -ggdb3 -std=gnu++98 -Wall -Werror -pedantic cyoa-step4.cpp
