#cyoa-step1: cyoa-step1.cpp page.hpp
#	g++ -o cyoa-step1 -std=gnu++98 -Wall -Werror -pedantic cyoa-step1.cpp
cyoa-step2: cyoa-step2.cpp page.hpp story.hpp
	g++ -o cyoa-step2 -std=gnu++98 -Wall -Werror -pedantic cyoa-step2.cpp
